### ISSUE TITLE
integrity test fail for streaming ZIP file

### ISSUE THREAD

**Issue by yingziwu** [101arrowz/fflate#113] opened 2021-12-19 10:39 UTC
**How to reproduce**

[reproduce.zip](https://github.com/101arrowz/fflate/files/7740631/default.zip)

1. download `reproduce.zip`.
2. unzip `reproduce.zip` and serve it, `python -m http.server`.
3. open `test.html` on browser,  http://127.0.0.1:8000/test.html .
4. test integrity of the downloaded zip, `7z t test.zip`

**The problem**

The download zip failed on the integrity test.

![image](https://user-images.githubusercontent.com/22741471/146672002-b00f75a4-1297-4e78-9b46-68719690ddc0.png)

```
$ 7z t \[夜小星\]末世里我变成了丧尸的同类.zip 

7-Zip [64] 17.04 : Copyright (c) 1999-2021 Igor Pavlov : 2017-08-28
p7zip Version 17.04 (locale=en_US.UTF-8,Utf16=on,HugeFiles=on,64 bits,16 CPUs x64)

Scanning the drive for archives:
1 file, 4104313 bytes (4009 KiB)

Testing archive: [夜小星]末世里我变成了丧尸的同类.zip
                
ERRORS:
Headers Error

--
Path = [夜小星]末世里我变成了丧尸的同类.zip
Type = zip
ERRORS:
Headers Error
Physical Size = 4104313
Characteristics = Local Central

    

Archives with Errors: 1

Open Errors: 1
```

**Comment by 101arrowz** [comment] 2021-12-19 18:46
Im not sure what `test.html` is (lease send the file), but if the archive still unzips properly, this is probably a duplicate of #92.

**Closed** 2022-01-18 23:34 UTC
